# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
climate: !include climate_controllers.yaml
sensor: !include sensors.yaml
scene: !include scenes.yaml
script: !include scripts.yaml

fontawesome:
simpleicons:

# Example configuration.yaml entry
rest_command:
  logicapps_execute:
    url: "https://logicapps-sharepoint-owners-example.azurewebsites.net:443/api/SharePointOwners/triggers/When_a_HTTP_request_is_received/invoke?api-version=2022-05-01&sp=%2Ftriggers%2FWhen_a_HTTP_request_is_received%2Frun&sv=1.0&sig=6VZragnt2Gd0nS8PtU_Azm_6nDN2VS9NX-MFNtzDRMI"
